apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubecounter

labels:
  - includeSelectors: true
    pairs:
      cluster: us-central1

resources:
  - ../../base

secretGenerator:
  - name: db-creds
    literals:
      - DB_USR=devuser
      - DB_PWD=devpass
