apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubecounter

resources:
  - namespace.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/httproute.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml

configMapGenerator:
  - name: postgres-init
    files:
      - postgres/init.sql
