apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubecounter

resources:
- ../../base

secretGenerator:
- literals:
  - DB_USR=devuser
  - DB_PWD=devpass
  name: db-creds
images:
- name: mmaous/kubecounter-client
  newName: mmaous/kubecounter-client
  newTag: e257622
