apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-postgres
  namespace: kubecounter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-postgres
  template:
    metadata:
      labels:
        app: app-postgres
    spec:
      containers:
        - name: postgres
          image: mmaous/kubecounter:postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: devuser
            - name: POSTGRES_PASSWORD
              value: devpass
            - name: POSTGRES_DB
              value: counterdb
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - devuser
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
