apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecounter-server
  namespace: kubecounter
  labels:
    app.kubernetes.io/name: kubecounter
    app.kubernetes.io/component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubecounter
      app.kubernetes.io/component: api

  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubecounter
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: kubecounter-server
          image: mmaous/kubecounter-server:dev-latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres-svc
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: counterdb
            - name: SERVER_PORT
              value: "8080"

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: DB_USR
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: DB_PWD
          livenessProbe:
            httpGet:
              path: /counters
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 40

          readinessProbe:
            httpGet:
              path: /counters
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 20
